sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mm-common

script: ./autogen.sh --enable-warnings=fatal && ./configure && make && make check
